version: "3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_DATABASE=devops
     - MYSQL_USER=root
     - MYSQL_PASSWORD=
    volumes:
     - devops:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: /spring-app
    restart: on-failure
    env_file: ./.env
    ports:
      -  8089:8089
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/devops?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  devops: